plugins {
    id 'java-library'
    id 'org.springframework.boot' version '3.4.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'maven-publish'
}
group = 'org.digitalmind.buildingblocks.templating'
version = '2.0.1'
ext {
    lombokVersion = '1.18.32'
    springOpenapiVersion = '2.6.0'
    springOpenapiVersion = '2.6.0'
    swaggerAnnotationsVersion = '2.2.25'
    jacksonDatabindVersion = '0.2.3'
}
java {
    sourceCompatibility = "21"
    targetCompatibility = "21"
}
bootJar {
    enabled = false
}
jar {
    archiveBaseName = "templating-core"
    enabled = true
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    implementation "org.digitalmind.buildingblocks.core:dynamic-cache-resolver:2.0.1"
    implementation "org.digitalmind.buildingblocks.core:jpautils:2.0.1"

    implementation "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    implementation 'commons-io:commons-io:2.14.0'
    implementation 'com.github.jknack:handlebars:4.2.1'
    implementation 'com.github.jknack:handlebars-helpers:4.1.2'
    implementation 'com.github.jknack:handlebars-guava-cache:4.1.2'
    implementation 'com.github.jknack:handlebars-jackson2:4.1.2'
    implementation 'org.beryx:handlebars-java-helpers:0.4.1'
    implementation 'org.thymeleaf:thymeleaf:3.1.2.RELEASE'
    implementation 'org.thymeleaf:thymeleaf-spring6:3.1.2.RELEASE'

    implementation "io.swagger.core.v3:swagger-annotations:${swaggerAnnotationsVersion}"
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springOpenapiVersion}"
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-api:${springOpenapiVersion}"
    implementation "org.openapitools:jackson-databind-nullable:${jacksonDatabindVersion}"
}

publishing {
    repositories {
        maven {
            name = "digitalmind"
            url = uri("https://maven.pkg.github.com/Digital-Mind-Solutions/maven-repository")
            credentials {
                username = project.findProperty("dm.ghub.user") ?: System.getenv("DM_GITHUB_USER")
                password = project.findProperty("dm.ghub.key") ?: System.getenv("DM_GITHUB_TOKEN")
            }
        }
    }
    publications {
        coreTemplate(MavenPublication) {
            from components.java
        }
    }
}
